version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/keplr-extension

    steps:
      - checkout
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
      - run: wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
      - run: sudo apt-get install apt-transport-https
      - run: sudo apt-get update && sudo apt-get install git-secret
      - run: echo $GPG_KEY > private.asc
      - run: echo $GPG_PASSPHRASE | gpg --batch --yes --passphrase-fd 0 --import ./private.asc
      - run: git-secret reveal
      - run: npm install
      - run: npm run lint-test
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
