version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/keplr-extension

    steps:
      - checkout
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: npm install
      - run: npm run lint-test
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
