name: Chromatic
on:
  push:
    branches:
      - 2.0/develop

jobs:
  chromatic:
    name: Upload to chromatic
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install --global yarn
      - run: sudo apt-get update
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: sudo apt-get install curl
      - run: curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.3/protoc-21.3-linux-x86_64.zip
      - run: unzip protoc-21.3-linux-x86_64.zip -d $HOME/protoc && echo $HOME/protoc/bin >> $GITHUB_PATH
      - run: yarn install --immutable
      - run: yarn ci
      - run: yarn workspace @keplr-wallet/extension chromatic --exit-zero-on-changes --auto-accept-changes
        env:
         CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
