name: Publish
on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: ["Lint", "Test"]
    types:
      - completed

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --global yarn
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: sudo apt-get install apt-transport-https ca-certificates
      - run: sudo sh -c "echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list"
      - run: wget -qO - 'https://gitsecret.jfrog.io/artifactory/api/gpg/key/public' | sudo apt-key add -
      - run: sudo apt-get update && sudo apt-get install git-secret
      - run: printf $GPG_KEY | base64 --decode > private.key
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - run: gpg --import --no-tty --batch --yes ./private.key
      - run: git-secret reveal -f -v -p $GPG_PASSPHRASE
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - run: cd packages/extension/src/keplr-torus-signin && yarn install --frozen-lockfile
      - run: yarn ci-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
