name: Test Unit

on:
  push:
    branches:
      - master
      - release/*

  pull_request:
    branches:
      - master
      - release/*

jobs:
  test-lint:
    name: Test code base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm install --global yarn
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: yarn ci
