name: Test

on:
  push:
    branches:
      - master
      - release/*
      - integration/*

  pull_request:
    branches:
      - master
      - release/*
      - integration/*

jobs:
  test:
    name: Test code base
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: sudo apt-get install libusb-1.0-0-dev
      - run: yarn ci
